import { Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';

/** Small "AI Generated" marker required on every AI-produced UI surface. */
export const AIGeneratedBadge = ({ className }: { className?: string }) => (
  <span
    className={cn(
      'inline-flex items-center gap-1 rounded-full bg-accent/15 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-accent',
      className,
    )}
    title="This content was generated by AI and should be reviewed."
  >
    <Sparkles className="h-3 w-3" /> AI Generated
  </span>
);
